LineLength:
  Enabled: false
MethodLength:
  Enabled: false
BlockLength:
  Enabled: false
ClassLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false